### PR TITLE
Fix bug#16506  on Returns Submitted on the 31st

### PR DESCRIPTION
**Pull request by sgrg1**
Bug 16506.
it was actually calculating Penalty incorrectly.

### CODE REVIEW

**Comment by martypowell** [comment]
@sgrg1 the bug says interest but in the overview it says penalty? is that just a typo?

**Comment by sgrg1** [comment]
There was no problem with interest . Penalty had problem

**Comment by martypowell** [comment]
@sgrg1 are you saying that Bug 16506 is not reproducible?

**Comment by sgrg1** [comment]
I could not recreate that bug when I pass 01/31/2020 as a submitted date but I saw incorrect penalty amount for that date.

**Comment by martypowell** [comment]
> I could not recreate that bug when I pass 01/31/2020 as a submitted date but I saw incorrect penalty amount for that date.

So you should update that particular bug as not able to reproduce and ensure with that the business owner confirms that is no longer an issue. Then log the bug that you found, so that the code can be reviewed based on that criteria.

**Pull request merged**
