### PR TITLE
Update currency control

### PR DESCRIPTION
**Pull request by martypowell**
Addresses #117 

@baltimorecounty/front-end-developers this is a stab at getting a cross browser currency component. I tried to "add" commas to the input and things got a bit messy, so for now i have left this to be a number input so that everything calculates okay.

### CODE REVIEW

**Comment by tmccoy529** [comment]
@martypowell I did find some issues with the input functionality in Edge and Chrome. It appears that the 0 placeholder doesn't delete when the box is selected. The reason why this is a problem is that it either adds a zero to the end of a number or to the front. You cannot delete this 0 until at least one other number is present. So you end up with either 012345.99 or worse 123450.99 then have to physically highlight the 0 and delete it. I would suggest removing the 0 placeholder and leaving it blank.

**Comment by sgrg1** [comment]
currency input allows you to enter number after default 0 , which does not look right .

**Comment by martypowell** [comment]
@tmccoy529 do you want to make the fix you suggested to get this one through?

**Comment by tmccoy529** [comment]
@martypowell @sgrg1 I have pushed up a commit that removes the 0 placeholder which was adding some confusion. We may end up having to add a regex to this to force a currency appearance but I think for now we are good on this component.

**Pull request merged**
